[files]
extend-exclude = [
  "*.lock",
  "*.rs",
  "*.vue",
  "*.js",
  "*.json",
  "*.ps1",
  "*.zip",
  "man",
  "build",
  "src-tauri/locales/app.yml",
]

[default.extend-words]
bu = "bu"
inout = "inout"
NEmpty = "NEmpty"
# GnuPG fingerprint field in `gpg --list-secret-keys --with-colons` output
fpr = "fpr"
FPR = "FPR"
