# Deactivation script generated by ESP-IDF Installation Manager (EIM)
# Mirrors {{activate_script_path}}. Undoes everything that the matching
# activate script set: unsets IDF env vars, strips toolchain PATH
# prefixes, drops the IDF shell functions/completions, and deactivates
# the Python venv.
#
# This script must be sourced, not executed:
#   source {{deactivate_script_path}}

# Fish guards source-vs-execute using `status is-interactive`. A script
# that is run directly (not sourced) lands here with a non-interactive
# status unless the user is in an interactive shell that explicitly
# sources it. We treat either case as "sourced" because the user
# invoked the script on purpose.
if not status is-interactive
    if test (count $argv) -ge 1; and test "$argv[1]" = "-h"
        echo "Usage: source {{deactivate_script_path}}"
        echo "Removes the ESP-IDF environment for {{idf_version}} from the current shell."
        # Use `return` rather than `exit`: in fish, `exit` inside a
        # sourced function/script terminates the entire shell session,
        # which would unexpectedly close the user's terminal.
        return 0
    end
end

# --- Strip matching PATH prefixes ---------------------------------------
# `addition_to_path` matches the colon-separated list that the activate
# script prepended to $PATH. We remove those exact entries (with and
# without the trailing slash) and rebuild PATH preserving the order of
# the remaining entries.
set -l addition_to_path "{{addition_to_path}}"

if test -n "$addition_to_path"
    set -l pfx_list (string split ":" "$addition_to_path")
    set -l new_path
    for entry in $PATH
        set -l skip 0
        for pfx in $pfx_list
            if test -z "$pfx"
                continue
            end
            switch "$entry/"
                case "$pfx/" "$pfx"
                    set skip 1
                    break
            end
        end
        if test "$skip" -eq 0
            set new_path $new_path $entry
        end
    end
    if set -q new_path[1]
        set -gx PATH $new_path
    else
        set -e PATH
    end
    echo "Removed IDF toolchain entries from PATH"
end

# --- Unset environment variables ----------------------------------------
# Fixed vars always set by the activation script.
for v in ESP_IDF_VERSION IDF_PATH IDF_TOOLS_PATH IDF_PYTHON_ENV_PATH \
         IDF_COMPONENT_LOCAL_STORAGE_URL ESP_ROM_ELF_DIR OPENOCD_SCRIPTS
    if set -q $v
        set -e $v
    end
end

# Tool variables written by the activate script as a semicolon list.
if set -q FISH_ENV_VAR_PAIRS; and test -n "$FISH_ENV_VAR_PAIRS"
    set -l pairs (string split ";" "$FISH_ENV_VAR_PAIRS")
    for pair in $pairs
        if test -n "$pair"
            set -l key (string split -m 1 ":" "$pair")[1]
            if set -q $key
                set -e $key
            end
        end
    end
    set -e FISH_ENV_VAR_PAIRS
end

# --- Deactivate the Python virtual environment --------------------------
if set -q VIRTUAL_ENV; and test -n "$VIRTUAL_ENV"
    if test -f "$VIRTUAL_ENV/bin/deactivate.fish"
        source "$VIRTUAL_ENV/bin/deactivate.fish"
        echo "Deactivated virtual environment at $VIRTUAL_ENV"
    else if test -f "$VIRTUAL_ENV/bin/deactivate"
        source "$VIRTUAL_ENV/bin/deactivate"
        echo "Deactivated virtual environment at $VIRTUAL_ENV (bash-style)"
    end
end
# Also drop a stray IDF_PYTHON_ENV_PATH that the activation set but that
# does not match a live venv.
set -e IDF_PYTHON_ENV_PATH 2>/dev/null

# --- Remove IDF tool functions and completions ---------------------------
for fn in idf.py esptool esptool.py espefuse espefuse.py espsecure \
         espsecure.py otatool.py parttool.py _idf_py_completion
    functions -e "$fn" 2>/dev/null
end

# Drop the idf.py tab completion registered by the activate script.
complete -c idf.py -e 2>/dev/null

set -e addition_to_path 2>/dev/null

echo "ESP-IDF environment deactivated."
