#!/bin/sh
# Deactivation script generated by ESP-IDF Installation Manager (EIM)
# Mirrors {{activate_script_path}}. Undoes everything that script set:
# unsets IDF env vars, strips the IDF PATH prefixes, drops the IDF
# shell functions/completions, and deactivates the Python venv.
#
# This script must be sourced, not executed:
#   . {{deactivate_script_path}}

# Only run when sourced; bail out if executed directly.
is_sourced() {
  if [ -n "$ZSH_VERSION" ]; then
      case $ZSH_EVAL_CONTEXT in *:file:*) return 0;; esac
  else
      case ${0##*/} in dash|-dash|bash|-bash|ksh|-ksh|sh|-sh) return 0;; esac
  fi
  return 1
}

if is_sourced; then
  sourced=1
else
  sourced=0
fi

if [ "$sourced" -eq 0 ]; then
    cat <<'USAGE'
This script should be sourced, not executed.

    . {{deactivate_script_path}}

It will:
  - unset ESP_IDF_VERSION, IDF_PATH, IDF_TOOLS_PATH, IDF_PYTHON_ENV_PATH,
    IDF_COMPONENT_LOCAL_STORAGE_URL, ESP_ROM_ELF_DIR, OPENOCD_SCRIPTS
    and every tool variable written by the matching activate script;
  - strip the toolchain path prefixes from $PATH (re-ordering the rest);
  - call the Python venv's `deactivate` if a venv is currently active;
  - remove the idf.py, esptool, espefuse, espsecure, otatool, parttool
    shell functions and the idf.py tab completion.
USAGE
    exit 1
fi

# --- Strip matching PATH prefixes ---------------------------------------
# `addition_to_path` matches the colon-separated list that the activate
# script prepended to $PATH. We remove those exact entries (with and
# without the trailing slash, in case a path is a directory) and rebuild
# PATH preserving the relative order of all other entries.
addition_to_path="{{addition_to_path}}"

strip_path_prefixes() {
    _old_path="$1"
    _new_path=""
    _old_ifs="$IFS"
    IFS=':'
    set -f
    for _entry in $_old_path; do
        _skip=0
        for _pfx in $addition_to_path; do
            [ -z "$_pfx" ] && continue
            case "$_entry/" in
                "$_pfx/"|"$_pfx")
                    _skip=1
                    break
                    ;;
            esac
        done
        if [ "$_skip" -eq 0 ]; then
            if [ -z "$_new_path" ]; then
                _new_path="$_entry"
            else
                _new_path="$_new_path:$_entry"
            fi
        fi
    done
    set +f
    IFS="$_old_ifs"
    printf '%s\n' "$_new_path"
}

if [ -n "$addition_to_path" ]; then
    _stripped="$(strip_path_prefixes "$PATH")"
    if [ -n "$_stripped" ]; then
        PATH="$_stripped"
    else
        unset PATH
    fi
    unset _stripped _entry _pfx _skip _new_path _old_ifs _old_path
    printf '%s\n' "Removed IDF toolchain entries from PATH"
fi

# --- Unset environment variables ----------------------------------------
# Fixed vars always set by the activation script.
for _v in ESP_IDF_VERSION IDF_PATH IDF_TOOLS_PATH IDF_PYTHON_ENV_PATH \
          IDF_COMPONENT_LOCAL_STORAGE_URL ESP_ROM_ELF_DIR OPENOCD_SCRIPTS; do
    if eval "[ \${$_v+x} ]"; then
        eval "unset $_v"
    fi
done

# Tool variables written by the activate script as a heredoc.
ENV_VAR_PAIRS=$(get_env_var_pairs 2>/dev/null) || ENV_VAR_PAIRS=""
if [ -n "$ENV_VAR_PAIRS" ]; then
    # Feed the heredoc directly into the while loop. A here-doc redirect
    # runs the consuming loop in the current shell (not a subshell), so
    # `unset` affects the parent. This avoids the mktemp/printf dance
    # (which can fail if /tmp is full or read-only) and an unsafe eval
    # round-trip on the variable name.
    while IFS= read -r _pair; do
        [ -n "$_pair" ] || continue
        _key="${_pair%%:*}"
        if [ -n "$_key" ]; then
            unset "$_key" 2>/dev/null || true
        fi
    done << EOF
$ENV_VAR_PAIRS
EOF
    unset _pair _key
fi

# --- Deactivate the Python virtual environment --------------------------
# If a venv was activated by the matching activate script, VIRTUAL_ENV
# will be set. We delegate to the standard venv deactivate function
# (which restores PATH/PYTHONHOME/PS1 and unsets its own helper vars)
# and then explicitly unset VIRTUAL_ENV -- the standard venv
# `deactivate` function does NOT clear it, so the caller's shell
# would otherwise still look "active" after sourcing this script.
if [ -n "${VIRTUAL_ENV:-}" ] && [ -f "${VIRTUAL_ENV}/bin/deactivate" ]; then
    # shellcheck disable=SC1090
    . "${VIRTUAL_ENV}/bin/deactivate"
    printf '%s\n' "Deactivated virtual environment at ${VIRTUAL_ENV}"
fi
unset VIRTUAL_ENV 2>/dev/null || true
# Also drop a stray IDF_PYTHON_ENV_PATH that the activation set but that
# does not match a live venv.
unset IDF_PYTHON_ENV_PATH 2>/dev/null || true

# --- Remove IDF tool functions and completions ---------------------------
for _fn in idf.py esptool esptool.py espefuse espefuse.py espsecure \
           espsecure.py otatool.py parttool.py _idf_py_custom_completion; do
    if command -v "$_fn" >/dev/null 2>&1; then
        unset -f "$_fn" 2>/dev/null || true
    fi
done

# Drop the idf.py tab completion registered by the activate script.
# The completion may have been registered as `complete -F _idf_py_custom_completion idf.py`
# (bash) or via `compdef` in zsh. Both are best-effort.
if [ -n "$BASH_VERSION" ]; then
    complete -r idf.py 2>/dev/null || true
fi
if [ -n "$ZSH_VERSION" ] && command -v compdef >/dev/null 2>&1; then
    # The activate script registered `_idfpy_completion` for `idf.py`; remove it.
    # `compdef -d` deletes the completion for the given command.
    if command -v compdef >/dev/null 2>&1; then
        compdef -d idf.py 2>/dev/null || true
    fi
    # Best-effort: drop the helper function and the cache entry.
    if typeset -f _idfpy_completion >/dev/null 2>&1; then
        unset -f _idfpy_completion 2>/dev/null || true
    fi
fi

unset _fn addition_to_path ENV_VAR_PAIRS 2>/dev/null || true

printf '%s\n' "ESP-IDF environment deactivated."
