@echo off
REM Deactivation script generated by ESP-IDF Installation Manager (EIM).
REM Mirrors the matching batch profile. Undoes everything that profile
REM set: unsets IDF env vars, strips toolchain PATH prefixes, removes
REM the IDF doskey aliases, and deactivates the Python venv.
REM
REM This script must be called from an interactive CMD, not executed:
REM     call "{{deactivate_script_path}}"

if /I "%~1"=="-h" goto usage
if /I "%~1"=="--help" goto usage

REM --- Strip matching PATH prefixes -------------------------------------
REM `add_paths_extras` matches the semicolon-separated list that the
REM activation script prepended to %PATH%. We remove those exact entries
REM (with and without the trailing backslash) and rejoin the rest.

setlocal EnableDelayedExpansion
set "ADD_PATHS_EXTRAS={{add_paths_extras}}"

set "NEW_PATH="
for %%P in ("%PATH:;=" "%") do (
    set "ENTRY=%%~P"
    if not "!ENTRY!"=="" (
        set "SKIP=0"
        for %%X in ("!ADD_PATHS_EXTRAS:;=" "%") do (
            set "PFX=%%~X"
            if not "!PFX!"=="" (
                if /I "!ENTRY!"=="!PFX!" set "SKIP=1"
            )
        )
        if "!SKIP!"=="0" (
            if defined NEW_PATH (
                set "NEW_PATH=!NEW_PATH!;!ENTRY!"
            ) else (
                set "NEW_PATH=!ENTRY!"
            )
        )
    )
)
endlocal & set "PATH=%NEW_PATH%"
echo Removed IDF toolchain entries from PATH

REM --- Unset environment variables --------------------------------------
REM Fixed vars always set by the activation script.
set "ESP_IDF_VERSION="
set "IDF_PATH="
set "IDF_TOOLS_PATH="
set "IDF_PYTHON_ENV_PATH="
set "IDF_COMPONENT_LOCAL_STORAGE_URL="
set "ESP_ROM_ELF_DIR="
set "OPENOCD_SCRIPTS="

REM Tool variables written by the activation script as a sequence of
REM `set KEY=VALUE` lines. We parse them out of the activation script
REM that lives next to this one and unset each.
REM
REM Use `delims== ` (both = and space) and tokens=1,2 so that a line
REM like `set IDF_PATH=C:\Espressif` is split into K=`set`, L=`IDF_PATH`
REM - using only `=` as the delimiter would leave K holding
REM `set IDF_PATH` (which then can't be unset as a var name).
set "ACTIVATE_SCRIPT={{activate_script_path}}"
if exist "%ACTIVATE_SCRIPT%" (
    for /f "usebackq tokens=1,2 delims== " %%K in ("%ACTIVATE_SCRIPT%") do (
        if /I "%%K"=="set" (
            if /I not "%%L"=="PATH" (
                set "%%L="
            )
        )
    )
)

REM --- Deactivate the Python virtual environment -------------------------
if defined VIRTUAL_ENV (
    if exist "%VIRTUAL_ENV%\Scripts\deactivate.bat" (
        call "%VIRTUAL_ENV%\Scripts\deactivate.bat"
        echo Deactivated virtual environment at %VIRTUAL_ENV%
    )
)
set "IDF_PYTHON_ENV_PATH="
set "VIRTUAL_ENV="

REM --- Remove IDF doskey aliases -----------------------------------------
REM The activation script registered doskey macros (idf.py, esptool, ...).
REM Reassigning each to an empty value drops just those macros. We
REM intentionally do NOT reinstall the doskey macro table here: doing
REM so would clear every doskey macro in the current session, including
REM any unrelated custom macros the user has defined.
for %%A in (idf.py esptool esptool.py espefuse espefuse.py espsecure ^
            espsecure.py otatool.py parttool.py) do (
    doskey %%A=
)

echo ESP-IDF environment deactivated.
goto :end

:usage
echo Usage:    call "{{deactivate_script_path}}"
echo.
echo Removes the ESP-IDF environment for {{idf_version}} from the current
echo CMD session.

:end
REM Clean up the local ACTIVATE_SCRIPT variable so it doesn't leak into
REM the caller's environment. There is no top-level setlocal in this
REM script (the PATH-stripping setlocal/endlocal above is self-contained
REM and uses endlocal & set to publish its result), so no endlocal is
REM needed here either.
set "ACTIVATE_SCRIPT="
