param(
    [Parameter(Mandatory=$false)]
    [switch]$h
)

# Deactivation script generated by ESP-IDF Installation Manager (EIM).
# Mirrors the matching PowerShell profile. Undoes everything that
# profile set: unsets IDF env vars, strips toolchain PATH prefixes,
# removes the IDF shell functions and tab completion, and deactivates
# the Python venv.
#
# This script must be dot-sourced:
#   . '{{deactivate_script_path}}'

if ($h) {
    @"
Usage: . '{{deactivate_script_path}}'

Removes the ESP-IDF environment for {{idf_version}} from the current
PowerShell session.
"@
    return
}

# --- Strip matching PATH prefixes ---------------------------------------
# `add_paths_extras` matches the semicolon-separated list that the
# activation script prepended to $env:PATH. We remove those exact
# entries (with and without the trailing backslash) and rejoin the rest.
$addPathsExtras = @('{{add_paths_extras}}' -split ';')

$pathEntries = $env:PATH -split ';' | Where-Object { $_ -ne '' }
$remaining = @()
foreach ($entry in $pathEntries) {
    $skip = $false
    foreach ($pfx in $addPathsExtras) {
        if ([string]::IsNullOrEmpty($pfx)) { continue }
        $entryNorm = $entry.TrimEnd('\')
        $pfxNorm = $pfx.TrimEnd('\')
        if ($entryNorm -eq $pfxNorm) {
            $skip = $true
            break
        }
    }
    if (-not $skip) {
        $remaining += $entry
    }
}

if ($remaining.Count -gt 0) {
    $env:PATH = ($remaining -join ';')
} else {
    Remove-Item Env:PATH -ErrorAction SilentlyContinue
}
Write-Host "Removed IDF toolchain entries from PATH"

# --- Unset environment variables ----------------------------------------
# Fixed vars always set by the activation script.
foreach ($v in @(
    'ESP_IDF_VERSION',
    'IDF_PATH',
    'IDF_TOOLS_PATH',
    'IDF_PYTHON_ENV_PATH',
    'IDF_COMPONENT_LOCAL_STORAGE_URL',
    'ESP_ROM_ELF_DIR',
    'OPENOCD_SCRIPTS'
)) {
    if (Test-Path "Env:$v") {
        Remove-Item "Env:$v" -ErrorAction SilentlyContinue
    }
}

# Tool variables written by the activation script as a hashtable.
if ($env_var_pairs) {
    foreach ($key in $env_var_pairs.Keys) {
        if (Test-Path "Env:$key") {
            Remove-Item "Env:$key" -ErrorAction SilentlyContinue
        }
    }
}

# --- Deactivate the Python virtual environment --------------------------
# If the matching activation script sourced the venv's Activate.ps1,
# VIRTUAL_ENV will be set. We call the venv's `deactivate` function.
if ($env:VIRTUAL_ENV) {
    $venvRoot = $env:VIRTUAL_ENV
    $deactivateScript = Join-Path $venvRoot 'Scripts\deactivate.ps1'
    if (Test-Path $deactivateScript) {
        try {
            & $deactivateScript
            Write-Host "Deactivated virtual environment at $venvRoot"
        } catch {
            Write-Warning "Failed to deactivate virtual environment at $venvRoot: $_"
        }
    }
}
# Drop a stray IDF_PYTHON_ENV_PATH that doesn't match a live venv.
if (Test-Path 'Env:IDF_PYTHON_ENV_PATH') {
    Remove-Item 'Env:IDF_PYTHON_ENV_PATH' -ErrorAction SilentlyContinue
}

# --- Remove IDF tool functions and completions ---------------------------
foreach ($fn in @(
    'Invoke-idfpy',
    'esptool',
    'esptool.py',
    'espefuse',
    'espefuse.py',
    'espsecure',
    'espsecure.py',
    'otatool.py',
    'parttool.py'
)) {
    if (Test-Path "Function:\$fn") {
        Remove-Item "Function:\$fn" -ErrorAction SilentlyContinue
    }
}

# The activation script created an alias `idf.py` -> Invoke-idfpy.
# Remove-Item on the alias' function entry removes both alias and target
# if the function is the only thing backing it. We just attempt the
# removal and ignore the error.
if (Test-Path 'Alias:idf.py') {
    Remove-Item 'Alias:idf.py' -ErrorAction SilentlyContinue
}

# Drop the idf.py tab completion registered by Register-ArgumentCompleter.
# Click's Register-ArgumentCompleter can also be unregistered with the
# same command, so we run the same call to undo the registration.
# The exact command issued by idf.py is wrapped in an argument completer
# script; we use a no-op source expression to drop the binding
# (PowerShell has no direct "unregister" verb in PSReadLine, so this is
# best-effort and silent on failure).
try {
    [System.Management.Automation.Language.ScriptBlock]::Create(
        "[System.Management.Automation.CommandCompletion]::Reset()"
    ).InvokeReturnAsIs() | Out-Null
} catch {
    # PSReadLine not loaded - completion was not registered.
}

# Remove the cached completer file written by `Register-ArgumentCompleter`,
# if it lives next to the activation script. Best-effort.
$cacheFile = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) 'idf_completion.cache'
if (Test-Path $cacheFile) {
    Remove-Item $cacheFile -ErrorAction SilentlyContinue
}

Write-Host 'ESP-IDF environment deactivated.'
