name: Tauri build

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
  workflow_dispatch:

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-13" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md

      - name: Install OpenSSL (Macos)
        if: matrix.os == 'macos-latest'
        run: brew install openssl

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev libssl-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Add +x permission to the binary
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          chmod +x src-tauri/target/release/eim
          chmod +x src-tauri/target/release/bundle/appimage/*.AppImage

      - name: Upload app Linux binary
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: eim-linux-x86_64-binary
          path: |
            src-tauri/target/release/eim
          if-no-files-found: error

      - name: Upload app .deb
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: eim-linux-x86_64-deb
          path: |
            src-tauri/target/release/bundle/deb/*.deb
          if-no-files-found: error

      - name: Upload app .rpm
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: eim-linux-x86_64-rpm
          path: |
            src-tauri/target/release/bundle/rpm/*.rpm
          if-no-files-found: error

      - name: Upload app .AppImage
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: eim-linux-x86_64-AppImage
          path: |
            src-tauri/target/release/bundle/appimage/*.AppImage
          if-no-files-found: error

      - name: Add +x permission to the binary
        if: matrix.platform == 'macos-latest'
        run: |
          chmod +x src-tauri/target/aarch64-apple-darwin/release/eim

      - name: Upload app MacOs binary
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest'
        with:
          name: eim-macos-aarch64-binary
          path: |
            src-tauri/target/aarch64-apple-darwin/release/eim
          if-no-files-found: error

      - name: Upload app MacOs
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest'
        with:
          name: eim-macos-aarch64-dmg
          path: |
            src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error

      - name: Upload app MacOs
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest'
        with:
          name: eim-macos-aarch64-app
          path: |
            src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app
          if-no-files-found: error

      - name: Add +x permission to the binary
        if: matrix.platform == 'macos-13'
        run: |
          chmod +x src-tauri/target/x86_64-apple-darwin/release/eim

      - name: Upload MacOs intel app binary
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-13'
        with:
          name: eim-macos-x86_64-binary
          path: |
            src-tauri/target/x86_64-apple-darwin/release/eim
          if-no-files-found: error

      - name: Upload app MacOs
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-13'
        with:
          name: eim-macos-x86_64-dmg
          path: |
            src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error

      - name: Upload app MacOs
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-13'
        with:
          name: eim-macos-x86_64-app
          path: |
            src-tauri/target/x86_64-apple-darwin/release/bundle/macos/*.app
          if-no-files-found: error

      - name: Upload app Windows binary
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: eim-windows-binary
          path: |
            src-tauri/target/release/eim.exe
          if-no-files-found: error

      - name: Upload app Windows
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: eim-windows-msi
          path: |
            src-tauri/target/release/bundle/msi/*.msi
          if-no-files-found: error
