name: Test cache invalidation
on:
  release:
    types:
      - created
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release/*
    paths:
      - "docs/**"
      - ".github/workflows/docs_build.yml"
  workflow_dispatch:

jobs:
  update-release-info:
    name: Update Release Information
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest release info
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DL_DISTRIBUTION_ID: ${{ secrets.DL_DISTRIBUTION_ID }}
          AWS_DEFAULT_REGION: ap-east-1
        run: |
          # GUI release info
          curl -s https://api.github.com/repos/espressif/idf-im-ui/releases/latest > eim_unified_release.json
          echo "Latest GUI release tag: $(jq -r .tag_name eim_unified_release.json)"
          aws s3 cp --acl=public-read "eim_unified_release.json" s3://espdldata/dl/eim/eim_unified_release.json
          aws cloudfront create-invalidation --distribution-id ${DL_DISTRIBUTION_ID} --paths "/dl/eim/eim_unified_release.json"
