import { expect } from "chai";
import { describe, it, before, after, afterEach } from "mocha";
import CLITestRunner from "../classes/CLITestRunner.class.js";
import logger from "../classes/logger.class.js";
import path from "path";
import fs from "fs";
import os from "os";

// Default EIM tool install / activation-script directory. Mirrors
// `Settings::default()` in src-tauri/src/lib/settings.rs: on POSIX
// it's $HOME/.espressif/tools, on Windows it's C:\\Espressif\\tools.
function getActivationScriptDir(installFolder) {
  if (os.platform() === "win32") {
    return "C:\\Espressif\\tools";
  }
  // `installFolder` is $HOME/.espressif by default, so the tools dir is a
  // sibling at $HOME/.espressif/tools.
  return path.join(path.dirname(installFolder), "tools");
}

// Returns the file paths of the activate / deactivate scripts for a
// given IDF version. Mirrors the names produced by `single_version_post_install`
// in src-tauri/src/lib/mod.rs and removed by `remove_activation_scripts`
// in src-tauri/src/lib/version_manager.rs.
function getScriptPaths(installFolder, idfVersion) {
  const dir = getActivationScriptDir(installFolder);
  if (os.platform() === "win32") {
    return {
      activate: path.join(dir, `Microsoft.${idfVersion}.PowerShell_profile.ps1`),
      deactivate: path.join(dir, `Microsoft.${idfVersion}.PowerShell_deactivate.ps1`),
    };
  }
  return {
    activate: path.join(dir, `activate_idf_${idfVersion}.sh`),
    deactivate: path.join(dir, `deactivate_idf_${idfVersion}.sh`),
  };
}

// This function performs a full CLI install of an IDF version, then
// verifies the new deactivation script lifecycle end-to-end:
//   1. both activate and deactivate scripts are created on disk;
//   2. sourcing the activate sets the IDF env vars;
//   3. sourcing the deactivate unsets them and strips the PATH prefixes;
//   4. running `eim remove <version>` deletes BOTH scripts.
//
// This is intended to be wired into the CLI test runner as a new
// `type: "deactivation"` scenario. It bundles a custom install (so the
// deactivation script gets generated by `single_version_post_install`)
// and the lifecycle verification, then leaves the install in place for
// the `runCleanUp` step in the suite runner.
export function runCLIDeactivationTest({
  id = 0,
  pathToEIM,
  args = [],
  idfVersion,
  installFolder,
}) {
  describe(`${id}- EIM deactivation lifecycle |`, function () {
    this.timeout(3600000);

    let testRunner = null;
    const scriptPaths = getScriptPaths(installFolder, idfVersion);

    before(async function () {
      this.timeout(3600000);
      logger.info(
        `Starting deactivation lifecycle test for IDF ${idfVersion} with args ${args.join(" ")}`
      );
      // Make sure the activate/deactivate scripts don't exist from a
      // previous run before we start the install.
      for (const p of [scriptPaths.activate, scriptPaths.deactivate]) {
        if (fs.existsSync(p)) {
          fs.rmSync(p, { force: true });
        }
      }
      testRunner = new CLITestRunner();
      await testRunner.start();
    });

    afterEach(function () {
      if (this.currentTest.state === "failed") {
        logger.info(`Test failed: ${this.currentTest.title}`);
        if (testRunner) {
          logger.info(
            `Terminal output: >>\r ${testRunner.output.slice(-2000)}`
          );
        }
      }
    });

    after(async function () {
      this.timeout(50000);
      try {
        if (testRunner) await testRunner.stop();
      } catch (error) {
        logger.info("Error cleaning up terminal");
        logger.info(`  ${error}`);
      } finally {
        testRunner = null;
      }
    });

    it("1- Should install IDF using specified parameters", async function () {
      this.timeout(3600000);
      logger.info(`Installing IDF ${idfVersion} for deactivation test`);
      testRunner.callEIM(pathToEIM, ["install", ...args]);
      // Wait for the install to finish the same way CLICustomInstall does.
      const startTime = Date.now();
      let installed = false;
      while (Date.now() - startTime < 3600000) {
        if (Date.now() - testRunner.lastDataTimestamp >= 600000) {
          logger.info("Exited due to idle terminal");
          break;
        }
        if (await testRunner.waitForOutput("panicked", 1000)) {
          logger.info("Rust app failure");
          break;
        }
        if (
          await testRunner.waitForOutput("Now you can start using IDF tools", 1000)
        ) {
          installed = true;
          break;
        }
        await new Promise((resolve) => setTimeout(resolve, 1000));
      }
      expect(installed, "Installation did not complete").to.be.true;
    });

    it("2- Should create both activate and deactivate scripts on disk", async function () {
      logger.info(
        `Verifying deactivation script at ${scriptPaths.deactivate}`
      );
      expect(
        fs.existsSync(scriptPaths.activate),
        `Activate script not found at ${scriptPaths.activate}`
      ).to.be.true;
      expect(
        fs.existsSync(scriptPaths.deactivate),
        `Deactivate script not found at ${scriptPaths.deactivate}`
      ).to.be.true;
      // Deactivate script must not be empty.
      const stat = fs.statSync(scriptPaths.deactivate);
      expect(stat.size, "Deactivate script is empty").to.be.greaterThan(0);
    });

    it("3- Sourcing deactivate should unset IDF env vars", async function () {
      // Use a fresh terminal so the source state is predictable.
      try {
        await testRunner.stop();
      } catch {
        /* already stopped */
      }
      testRunner = new CLITestRunner();
      await testRunner.start();

      // Source the activation script first. On POSIX the runner is
      // bash; on Windows it's powershell. Both `source` / `.` work.
      const sourceCmd =
        os.platform() === "win32"
          ? `. "${scriptPaths.activate}"`
          : `source "${scriptPaths.activate}"`;
      const deactCmd =
        os.platform() === "win32"
          ? `. "${scriptPaths.deactivate}"`
          : `source "${scriptPaths.deactivate}"`;

      testRunner.sendInput(sourceCmd);
      // The activate script prints "Environment setup complete..." or
      // powershell "IDF PowerShell Environment" once it finishes. Wait
      // for either, with a generous timeout.
      const activated =
        (await testRunner.waitForOutput(
          "Environment setup complete for the current shell session",
          60000
        )) ||
        (await testRunner.waitForOutput(
          "IDF PowerShell Environment",
          60000
        ));
      expect(activated, "Activation script did not produce expected banner").to.be.true;

      // Verify IDF_TOOLS_PATH is set after activation. We use the
      // runner's runAndCapture which uses a sentinel to delimit the
      // output and is reliable on both POSIX and Windows.
      const activateCheck = await testRunner.runAndCapture(
        os.platform() === "win32"
          ? `Write-Host "IDF_PATH=$env:IDF_PATH"; Write-Host "IDF_TOOLS_PATH=$env:IDF_TOOLS_PATH"; Write-Host "ESP_IDF_VERSION=$env:ESP_IDF_VERSION"; Write-Host "VIRTUAL_ENV=$env:VIRTUAL_ENV"`
          : `echo "IDF_PATH=$IDF_PATH" ; echo "IDF_TOOLS_PATH=$IDF_TOOLS_PATH" ; echo "ESP_IDF_VERSION=$ESP_IDF_VERSION" ; echo "VIRTUAL_ENV=$VIRTUAL_ENV"`,
        "ACTIVATE_DONE",
        30000
      );
      expect(
        activateCheck.output,
        "IDF_TOOLS_PATH should be set after activation"
      ).to.include("IDF_TOOLS_PATH=");
      // The output buffer strips newlines, so look for the marker
      // followed by an actual value. IDF_TOOLS_PATH must not be empty.
      const idfToolsPathMatch = activateCheck.output.match(
        /IDF_TOOLS_PATH=([^\s;]*)/
      );
      expect(
        idfToolsPathMatch && idfToolsPathMatch[1].length > 0,
        `IDF_TOOLS_PATH should be non-empty after activation. Output: ${activateCheck.output}`
      ).to.be.true;

      // Now source the deactivate script and re-check the same vars.
      testRunner.sendInput(deactCmd);
      const deactDone = await testRunner.runAndCapture(
        "echo DEACT_DONE",
        "DEACT_DONE",
        30000
      );
      expect(
        deactDone.output,
        `Deactivation script did not finish. Output: ${deactDone.output}`
      ).to.include("ESP-IDF environment deactivated.");

      const deactCheck = await testRunner.runAndCapture(
        os.platform() === "win32"
          ? `Write-Host "IDF_PATH=$env:IDF_PATH"; Write-Host "IDF_TOOLS_PATH=$env:IDF_TOOLS_PATH"; Write-Host "ESP_IDF_VERSION=$env:ESP_IDF_VERSION"; Write-Host "VIRTUAL_ENV=$env:VIRTUAL_ENV"`
          : `echo "IDF_PATH=$IDF_PATH" ; echo "IDF_TOOLS_PATH=$IDF_TOOLS_PATH" ; echo "ESP_IDF_VERSION=$ESP_IDF_VERSION" ; echo "VIRTUAL_ENV=$VIRTUAL_ENV"`,
        "POST_DONE",
        30000
      );

      // After deactivation:
      //   - IDF_PATH / IDF_TOOLS_PATH / VIRTUAL_ENV must be empty
      //     (var set to nothing, or not set at all).
      //   - ESP_IDF_VERSION must not look like a version (e.g. "5.3").
      for (const varName of [
        "IDF_PATH",
        "IDF_TOOLS_PATH",
        "VIRTUAL_ENV",
      ]) {
        const re = new RegExp(`${varName}=([^\\s;]*)`);
        const m = deactCheck.output.match(re);
        const value = m ? m[1] : null;
        expect(
          !value || value.length === 0,
          `After deactivation, ${varName} should be empty, got '${value}'.\nOutput: ${deactCheck.output}`
        ).to.be.true;
      }
      const espMatch = deactCheck.output.match(/ESP_IDF_VERSION=([^\s;]*)/);
      const espValue = espMatch ? espMatch[1] : null;
      expect(
        !espValue || !/^\d/.test(espValue),
        `After deactivation, ESP_IDF_VERSION should be empty, got '${espValue}'.\nOutput: ${deactCheck.output}`
      ).to.be.true;
    });

    it("4- eim remove should delete both activate and deactivate scripts", async function () {
      this.timeout(120000);
      try {
        await testRunner.stop();
      } catch {
        /* already stopped */
      }
      testRunner = new CLITestRunner();
      await testRunner.start();

      testRunner.callEIM(pathToEIM, ["remove", idfVersion]);
      const removed = await testRunner.waitForOutput(
        `Removed version: ${idfVersion}`,
        60000
      );
      expect(removed, "eim remove did not report success").to.be.true;

      // Give the OS a moment to settle on the file deletion.
      await new Promise((resolve) => setTimeout(resolve, 2000));

      expect(
        fs.existsSync(scriptPaths.activate),
        `Activate script should be gone after remove: ${scriptPaths.activate}`
      ).to.be.false;
      expect(
        fs.existsSync(scriptPaths.deactivate),
        `Deactivate script should be gone after remove: ${scriptPaths.deactivate}`
      ).to.be.false;
    });
  });
}
